'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../core.js'),R=require('../recovery.js'),P=require('../proxy_manager.js');
const {loadWorker}=require('./helpers/worker_vm.cjs');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const URL1='https://www.avito.ru/test/nastolnye_kompyutery/pc_12345678';
const base='Режим:\nAVITO_UI\nСтраница:\nhttps://www.avito.ru/all/nastolnye_kompyutery?q=пк\nШаги:\n';
function fixture(t,opts={}){const w=loadWorker(opts);t.after(()=>w.dispose());return w;}
function cp(w,n=3,extra={}){return {kind:'assistant_explicit_public_url_queue',parent_tab_id:7,parent_window_id:2,parent_url:w.tabs.get(7).url,candidates:Array.from({length:n},(_,i)=>({href:URL1.replace('12345678',String(12345678+i))})),cursor:0,batch_size:3,card_gap_ms:0,details:[],failed:[],cards_closed:0,status:'running',...extra};}
async function dispatch(w,type,sender,extra={}){return new Promise(r=>[...w.chrome.runtime.onMessage.listeners][0]({type,...extra},sender,r));}
const ui=w=>({id:w.chrome.runtime.id,url:w.chrome.runtime.getURL('popup.html')});
const chat=w=>({id:w.chrome.runtime.id,url:w.tabs.get(1).url,frameId:0,tab:w.tabs.get(1)});

for(const n of [1,3,6,7,30])test(`queue explicit count ${n} preserved`,()=>{let p=C.parseCommandForm(base.replace('Шаги:\n','')+'Очередь:\n'+Array.from({length:n},(_,i)=>URL1.replace('12345678',String(12345678+i))).join('\n')+'\nШаги:\nСобери публичные данные лотов из очереди пакетом '+n+'.');assert.equal(p.valid,true,JSON.stringify(p.errors));assert.equal(p.ui_plan.steps[0].selected_urls.length,n);});
for(const n of [31,32,100])test(`queue ${n} rejects instead of dropping URLs`,()=>{let p=C.parseCommandForm(base.replace('Шаги:\n','')+'Очередь:\n'+Array.from({length:n},(_,i)=>URL1.replace('12345678',String(12345678+i))).join('\n')+'\nШаги:\nСобери публичные данные лотов из очереди пакетом 3.');assert.equal(p.valid,false);});
for(const url of ['https://www.avito.ru/profile/messenger','https://www.avito.ru/api/items','https://u:secret@www.avito.ru/all','https://www.avito.ru:8443/all','https://www.avito.ru.evil.example/all','http://www.avito.ru/all'])test(`private/foreign URL rejected ${url}`,()=>{assert.equal(C.parseCommandForm(base.replace('https://www.avito.ru/all/nastolnye_kompyutery?q=пк',url)+'Собери до 30 видимых объявлений.').valid,false);});
for(const action of ['Подожди 25 секунд.','Введи "'+ 'a'.repeat(161) +'" в поле поиска.','Прыгни выше.\nСобери до 30 видимых объявлений.','Собери до 121 видимых объявлений.'])test(`command never silently changes requested semantics ${action.slice(0,30)}`,()=>assert.equal(C.parseCommandForm(base+action).valid,false));

test('queue evidence survives projection, persistence, JSON message, and human report',async t=>{const w=fixture(t,{onMessage(id,m,done,{finish}){if(m.type==='AF_SEQUENTIAL_READ_PUBLIC_LISTING'){finish(done,{ok:true,result:{details:{href:URL1,title:'Public PC',price:'10000',availability:'RESERVED',captured_at:'2026-09-10T01:00:00Z',source:'public_dom',direct_delivery:{confirmed:true,exact_text:'Купить с доставкой',element_tag:'button',visible:true,enabled:true,marker:'new-delivery'},description:'описание',truncated_fields:['description'],blocked_reason:null}}});return true;}return false;}});const s=await w.seed({status:'AVITO_TAB_ACTIVE'});let q=cp(w,1);await w.h.runSequentialCardBatch(s,w.tabs.get(7),q);const stored=(await w.h.getState()).sequential_review;const publicProjection=JSON.parse(JSON.stringify(w.ctx.compactSequentialCheckpoint(stored)));assert.equal(publicProjection.collected[0].direct_delivery.confirmed,true);const text=C.formatUiActionPlanReport({avito:{sequential_review:publicProjection}});assert.match(text,/подтверждена активным/);assert.match(text,/new-delivery/);assert.match(text,/RESERVED/);assert.match(text,/description/);});
test('unread queue has zero facts and explicit pending URLs, not empty fake results',t=>{const w=fixture(t);const p=w.ctx.compactSequentialCheckpoint(cp(w));assert.equal(p.collected.length,0);assert.equal(p.details_collected,0);assert.equal(p.pending.length,3);});
test('detail and cursor are stored BEFORE close; no reread after close-before-receipt crash',async t=>{const w=fixture(t);const s=await w.seed({status:'AVITO_TAB_ACTIVE'});let q=cp(w,2);q.batch_size=1;let captured;
const remove=w.chrome.tabs.remove;w.chrome.tabs.remove=(id,done)=>{captured=structuredClone(w.local[C.STORAGE.state].sequential_review);assert.equal(captured.cursor,1);assert.equal(captured.details.length,1);assert.equal(captured.pending_close.child_tab_id,id);remove(id,done);};
await w.h.runSequentialCardBatch(s,w.tabs.get(7),q);const w2=fixture(t,{local:w.local,session:w.session});let state=await w2.h.getState();await w2.h.saveState({...state,sequential_review:captured});const r=await w2.h.runSequentialCardBatch(state,w2.tabs.get(7),captured);assert.equal(r.checkpoint.cursor,1);assert.equal(r.checkpoint.close_receipt_unknown,1);assert.equal(w2.calls.filter(x=>x[2]==='AF_SEQUENTIAL_READ_PUBLIC_LISTING').length,0);});
test('restart after persisted child creation navigates owned blank child exactly once',async t=>{const w=fixture(t);let q=cp(w,1,{in_flight:{child_tab_id:40,cursor:0,href:URL1,stage:'CREATED'}});w.tabs.set(40,{id:40,url:'about:blank',openerTabId:7,windowId:2,status:'complete'});const s=await w.seed({status:'AVITO_TAB_ACTIVE',sequential_review:q});const r=await w.h.runSequentialCardBatch(s,w.tabs.get(7),q);assert.equal(r.checkpoint.cursor,1);assert.equal(w.calls.filter(x=>x[0]==='navigate').length,1);assert.equal(w.calls.find(x=>x[0]==='navigate')[1],40);});
test('batch boundary is stable after a worker restart',async t=>{const w=fixture(t);let q=cp(w,8,{cursor:2,batch_operation_key:'test-run:command1',batch_start_cursor:0,batch_end_cursor:3});const s=await w.seed({status:'AVITO_TAB_ACTIVE',sequential_review:q});const r=await w.h.runSequentialCardBatch(s,w.tabs.get(7),q);assert.equal(r.checkpoint.cursor,3);assert.equal(r.checkpoint.status,'paused_after_test_batch');assert.equal(r.attempted,1);});
test('gap persists a no-earlier deadline and returns without holding a batch event',async t=>{const w=fixture(t);let q=cp(w,2,{card_gap_ms:2000});const s=await w.seed({status:'AVITO_TAB_ACTIVE'});const r=await w.h.runSequentialCardBatch(s,w.tabs.get(7),q);assert.equal(r.deferred_recovery,true);assert.equal(r.checkpoint.cursor,1);assert.equal((await w.h.getState()).status,'SEQUENTIAL_GAP_WAIT');assert.ok(r.checkpoint.resume_after>Date.now());const calls=w.calls.length;await w.h.recoverRuntimeOnWake();assert.equal(w.calls.slice(calls).filter(x=>x[0]==='navigate'||x[0]==='reload').length,0);});
test('failed persistence does not close the only evidence tab or advance durable cursor',async t=>{const w=fixture(t);const s=await w.seed({status:'AVITO_TAB_ACTIVE'});const write=w.chrome.storage.local.set;let failed=false;w.chrome.storage.local.set=(values,done)=>{if(!failed&&values[C.STORAGE.state]?.phase==='SEQUENTIAL_RESULT_COMMITTED'){failed=true;queueMicrotask(()=>{w.chrome.runtime.lastError={message:'QUOTA_BYTES quota exceeded'};done();w.chrome.runtime.lastError=null;});return;}write(values,done);};const r=await w.h.runSequentialCardBatch(s,w.tabs.get(7),cp(w,1));assert.equal(r.checkpoint.cursor,0);assert.equal(r.checkpoint.details.length,0);assert.equal(w.calls.filter(x=>x[0]==='close').length,0);assert.match(r.blocked_reason,/quota/i);});
test('retained foreign child is never navigated/read/closed',async t=>{const w=fixture(t);w.tabs.set(40,{id:40,windowId:999,openerTabId:12,url:URL1});let q=cp(w,1,{in_flight:{cursor:0,child_tab_id:40,href:URL1}});const s=await w.seed({status:'AVITO_TAB_ACTIVE',sequential_review:q});const r=await w.h.runSequentialCardBatch(s,w.tabs.get(7),q);assert.equal(r.checkpoint.cursor,0);assert.match(r.blocked_reason,/OWNERSHIP/);assert.ok(w.tabs.has(40));});
for(const status of [404,410])test(`negative HTTP ${status} not confused with unread next URL`,async t=>{const w=fixture(t,{onMessage(id,m,done,{finish}){if(m.type==='AF_SEQUENTIAL_READ_PUBLIC_LISTING'){finish(done,{ok:true,result:{details:{blocked_reason:`LISTING_UNAVAILABLE_HTTP_${status}`}}});return true;}return false;}});const s=await w.seed({status:'AVITO_TAB_ACTIVE'});const r=await w.h.runSequentialCardBatch(s,w.tabs.get(7),cp(w,1));assert.equal(r.checkpoint.cursor,1);const out=w.ctx.compactSequentialCheckpoint(r.checkpoint);assert.equal(out.collected.length,0);assert.equal(out.failed.length,1);assert.equal(out.pending.length,0);});

for(const [raw,expected] of [['120',120000],['0',0],['-5',null],['1.2',null],['garbage',null]])test(`Retry-After seconds syntax ${raw}`,()=>assert.equal(R.retryAfterTime(raw,1000),expected===null?null:1000+expected));
test('Retry-After HTTP-date and overflow do not cause early retries',()=>{assert.equal(R.retryAfterTime('Thu, 10 Sep 2026 08:00:00 GMT',0),Date.parse('2026-09-10T08:00:00Z'));assert.equal(R.retryAfterTime('999999999999999999999',0),Number.MAX_SAFE_INTEGER);});
test('Retry-After longer than automatic budget is preserved, no reload/proxy/provider request',async t=>{const w=fixture(t);const s=await w.seed({ui_action_plan:{steps:[{type:'COLLECT_EXPLICIT_LISTING_QUEUE'}]}});await w.h.recordNetworkEvidence({tabId:7,requestId:'req',url:w.tabs.get(7).url},'started');await w.h.recordNetworkEvidence({tabId:7,requestId:'req',url:w.tabs.get(7).url,statusCode:429,responseHeaders:[{name:'Retry-After',value:'600'},{name:'Set-Cookie',value:'PRIVATE'}]},'headers');const r=await w.h.recoverAvitoConnectionAndReload(s,w.tabs.get(7),1,'429',{kind:'sequential_card',parent_tab_id:7,cursor:0,target_url:URL1},'RATE_LIMIT');assert.equal(r.status,'SEQUENTIAL_RECOVERY_BLOCKED');assert.match(r.blocked_reason,/WAIT_EXCEEDS/);assert.equal(w.calls.filter(x=>x[0]==='pac'||x[0]==='reload').length,0);assert.ok(w.local.af_avito_rate_gate_v129.until>Date.now()+590000);assert.equal(JSON.stringify(w.local).includes('PRIVATE'),false);});
test('rate-limit recovery works DIRECT and does not call Proxy.Market',async t=>{let requests=0;const w=fixture(t,{fetch:async()=>{requests++;throw Error('not expected');}});const s=await w.seed();await w.h.saveProxyRuntime({...await w.h.getProxyRuntime(),mode:'direct'});const r=await w.h.recoverAvitoConnectionAndReload(s,w.tabs.get(7),1,'429',null,'RATE_LIMIT');assert.equal(r.connection_recovery.prepared.strategy,'COOLDOWN_SAME_ROUTE');assert.equal(requests,0);assert.equal(w.calls.filter(x=>x[0]==='pac').length,0);assert.equal(w.calls.filter(x=>x[0]==='reload').length,1);});
test('alarm scheduling never moves an existing earlier future wake later',async t=>{const w=fixture(t);const a=Date.now()+30000;await w.ctx.scheduleOwnedAlarm('gate',a);await w.ctx.scheduleOwnedAlarm('gate',a+5000);assert.equal(w.alarms.get('gate').when,a);await w.ctx.scheduleOwnedAlarm('gate',a-5000);assert.equal(w.alarms.get('gate').when,a-5000);});
test('status read is pure: no replay/proxy/navigation on GET_VIEW',async t=>{const w=fixture(t);await w.seed();const before=w.calls.length;await w.ctx.view();assert.equal(w.calls.slice(before).filter(x=>['reload','navigate','pac'].includes(x[0])||x[2]==='AF_EXECUTE_AVITO_UI_PLAN').length,0);});
for(const type of ['AF_START','AF_STOP','AF_CONTINUE_REPORT','AF_GET_VIEW','AF_PROXY_KEY_EXPORT','AF_PROXY_PROFILE_DETAILS'])test(`content script cannot invoke popup privilege ${type}`,async t=>{const w=fixture(t);await w.seed();const r=await dispatch(w,type,chat(w));assert.equal(r.ok,false);assert.match(r.error,/SENDER_REQUIRED/);});
for(const senderKind of ['foreignId','iframe','wrongHost'])test(`capture channel rejects ${senderKind}`,async t=>{const w=fixture(t);const s=chat(w);if(senderKind==='foreignId')s.id='external';if(senderKind==='iframe')s.frameId=4;if(senderKind==='wrongHost')s.url='https://evil.example/';const r=await dispatch(w,'AF_CAPTURE_ACTIVITY',s);assert.equal(r.ok,false);});
test('same pinned chat initial command polling can recover after content reload',async t=>{const w=fixture(t);await w.seed({status:'WAITING_FOR_ASSISTANT_WRITING_BLOCK'});const r=await w.ctx.recoverContinuousPromptPoll({identity:w.identity},chat(w));assert.equal(r.data.resume,true);});

test('disable Finder clears only own setting and restores system proxy precedence',async t=>{const system={mode:'fixed_servers',rules:{singleProxy:{host:'corporate.example',port:8080}}};const w=fixture(t,{systemProxy:system});await w.seed({status:'WAITING_FOR_NEXT_ASSISTANT_FORM'});const r=await w.ctx.setProxyDirect();assert.equal(r.ok,true);assert.equal(w.calls.filter(x=>x[0]==='proxy_clear').length,1);assert.deepEqual(w.effective().value,system);assert.equal((await w.h.getProxySecret()).active_profile_id,null);});
for(const value of ['10000x','1.5','Infinity','1e4'])test(`proxy integer ${value} rejects instead of parseInt coercion`,()=>assert.equal(P.int(value,null),null));
for(const value of [':','::::','999.1.2.3','-bad.example','bad..example','a'.repeat(254)])test(`proxy host invalid ${value.slice(0,20)}`,()=>assert.equal(P.validProxyHost(value),false));
test('password bytes survive normalization including leading/trailing spaces',()=>{const p=P.normalizeProxyMarketRecord({id:5,host:'pool.proxy.market',port:10000,login:' user ',password:' pass ',package_id:1});assert.equal(p.password,' pass ');assert.equal(p.login,' user ');assert.equal(P.normalizeProxyMarketRecord({id:5,host:'pool.proxy.market',port:'10000junk',password:'p',login:'l',package_id:1}),null);});
for(const value of ['not_rotation','3minutes',61,-2])test(`invalid create rotation ${value} never silently switches to Sticky`,()=>assert.throws(()=>P.apiCreateProxyBody({package_id:1,rotation:value}),/ROTATION_INVALID/));
test('unknown outcome of manual endpoint POST blocks duplicate after worker restart; explicit reconciliation does not POST',async t=>{let count=0;const w=fixture(t,{apiKey:'fixture-key',fetch:async()=>{count++;throw Error('lost response');}});await w.seed({status:'WAITING_FOR_NEXT_ASSISTANT_FORM'});const a=await w.ctx.createProxyMarketEndpoint({package_id:68507,rotation:0});assert.equal(a.ok,false);assert.equal(w.local.af_proxy_manual_create_v129.state,'DISPATCHED_OUTCOME_UNKNOWN');const w2=fixture(t,{local:w.local,session:w.session,fetch:async()=>{count++;throw Error('must not dispatch');}});const b=await w2.ctx.createProxyMarketEndpoint({package_id:68507,rotation:0});assert.match(b.error,/OUTCOME_UNKNOWN/);assert.equal(count,1);const r=await dispatch(w2,'AF_PROXY_CREATE_ACKNOWLEDGE',ui(w2),{confirmed:true});assert.equal(r.ok,true);assert.equal(count,1);});
test('bounded stream cancels on byte limit before allocating full response',async()=>{let pulled=0,cancelled=false;const stream=new ReadableStream({pull(controller){pulled++;controller.enqueue(new Uint8Array(32));},cancel(){cancelled=true;}});const response=await R.fetchBounded(async()=>new Response(stream),'https://fixture',{}, {max_bytes:64});await assert.rejects(response.text(),/TOO_LARGE/);assert.equal(cancelled,true);assert.ok(pulled<=4);});
test('discard closes unused response and aborts transport without reading body',async()=>{let signal;const response=await R.fetchBounded(async(_,o)=>{signal=o.signal;return {ok:true,status:200,text:async()=>''};},'https://fixture');response.discard();assert.equal(signal.aborted,true);});
test('bounded response body can only be consumed once',async()=>{const r=await R.fetchBounded(async()=>new Response('{"ok":true}'),'https://fixture');assert.equal((await r.json()).ok,true);await assert.rejects(r.text(),/ALREADY_CONSUMED/);});
for(const action of ['Нажми "Показать телефон".','Нажми "phone".'])test('phone revelation rejected by command contract '+action,()=>assert.equal(C.parseCommandForm(base+action).valid,false));
test('reused private Avito tab is rejected before readiness injection',async t=>{const w=fixture(t);w.tabs.get(7).url='https://www.avito.ru/profile/messenger';await w.seed();await assert.rejects(w.ctx.requireReadyAvitoTarget(7,2),/PUBLIC_AVITO_PAGE_REQUIRED/);assert.equal(w.calls.filter(c=>c[0]==='execute').length,0);});

test('card text truncation is explicit in recipient report',()=>{const t=C.formatUiActionPlanReport({avito:{listings:[{title:'PC',card_text:'x'.repeat(1400),truncated_fields:['card_text']}]}});assert.match(t,/ограничен 1400/);});
