'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ROOT=path.resolve(__dirname,'../..'),OUT=process.env.AF_SCENARIO_OUT||path.join(ROOT,'qa/v134/blocks/block02.json');
const src=fs.readFileSync(path.join(ROOT,'core.js'),'utf8');const ctx={console,URL,Date,Math,globalThis:null};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(src,ctx);const C=ctx.AvitoFinderCore;
const U='https://www.avito.ru/moskva/tovary_dlya_kompyutera/monitor_27_ips_8348999864';
const S='https://www.avito.ru/all/tovary_dlya_komputera/monitory?q=monitor&s=104';
function form({page=S,steps='Собери до 30 видимых карточек текущей выдачи.',queue='',gap='',mode='AVITO_UI'}={}){return `Режим:\n${mode}\nСтраница:\n${page}\n${gap?`Пауза между карточками:\n${gap}\n`:''}${queue?`Очередь:\n${queue}\n`:''}Шаги:\n${steps}`}
const cases=[];function add(id,name,input,expected,check){let actual;let status='FAIL';try{const p=C.parseCommandForm(input);actual={valid:p.valid,errors:[...p.errors],mode:p.mode,steps:(p.ui_plan?.steps||[]).map(x=>({type:x.type,batch:x.batch,limit:x.limit,selected_urls:x.selected_urls?.length})),page:p.ui_plan?.page_url,gap:p.ui_plan?.sequential_card_gap_ms};status=check(p)?'PASS':'FAIL';}catch(e){actual={error:String(e)}}cases.push({id,name,input:input.slice(0,500),emulation:'production core.js parseCommandForm',expected,actual,status});}
add('B02-S01','valid collection',form(), 'valid AVITO_UI; COLLECT_LISTINGS limit 30',p=>p.valid&&p.ui_plan.steps[0].type==='COLLECT_LISTINGS'&&p.ui_plan.steps[0].limit===30);
add('B02-S02','explicit queue 6',form({page:U,queue:Array.from({length:6},(_,i)=>U.replace('8348999864',String(8348999864+i))).join('\n'),steps:'Собери публичные данные лотов из очереди пакетом 6.'}),'valid queue; 6 URLs; batch 6',p=>p.valid&&p.ui_plan.steps[0].type==='COLLECT_EXPLICIT_LISTING_QUEUE'&&p.ui_plan.steps[0].selected_urls.length===6&&p.ui_plan.steps[0].batch===6);
add('B02-S03','explicit queue max 30',form({page:U,queue:Array.from({length:30},(_,i)=>U.replace('8348999864',String(8348999864+i))).join('\n'),steps:'Собери публичные данные лотов из очереди пакетом 30.'}),'valid queue 30, no truncation',p=>p.valid&&p.ui_plan.steps[0].selected_urls.length===30);
add('B02-S04','explicit queue 31',form({page:U,queue:Array.from({length:31},(_,i)=>U.replace('8348999864',String(8348999864+i))).join('\n'),steps:'Собери публичные данные лотов из очереди пакетом 30.'}),'reject UI_PLAN_EXPLICIT_QUEUE_TOO_LARGE',p=>!p.valid&&p.errors.includes('UI_PLAN_EXPLICIT_QUEUE_TOO_LARGE'));
add('B02-S05','missing page',`Режим:\nAVITO_UI\nШаги:\nСобери до 30 видимых карточек.`, 'reject UI_PLAN_PAGE_REQUIRED',p=>!p.valid&&p.errors.includes('UI_PLAN_PAGE_REQUIRED'));
add('B02-S06','private/account path',form({page:'https://www.avito.ru/profile',steps:'Собери до 10 видимых карточек.'}),'reject page not allowed',p=>!p.valid&&p.errors.includes('UI_PLAN_PAGE_NOT_ALLOWED'));
add('B02-S07','unknown step',form({steps:'Станцуй вокруг карточки.'}),'reject unsupported/step required',p=>!p.valid&&(p.errors.includes('UI_PLAN_UNSUPPORTED_STEP')||p.errors.includes('UI_PLAN_STEP_REQUIRED')));
add('B02-S08','forbidden phone click',form({steps:'Нажми «Показать телефон».'}),'reject forbidden action',p=>!p.valid&&p.errors.includes('UI_PLAN_FORBIDDEN_ACTION'));
add('B02-S09','wait 5 sec',form({steps:'Подожди 5 сек.'}),'accept WAIT 5000ms',p=>p.valid&&p.ui_plan.steps[0].type==='WAIT'&&p.ui_plan.steps[0].duration_ms===5000);
add('B02-S10','wait 6 sec',form({steps:'Подожди 6 сек.'}),'reject wait out of range',p=>!p.valid&&p.errors.includes('UI_PLAN_WAIT_OUT_OF_RANGE'));
add('B02-S11','card gap 5000ms',form({page:U,queue:U,steps:'Собери публичные данные лотов из очереди пакетом 1.',gap:'5000 мс'}),'accept exact gap 5000',p=>p.valid&&p.ui_plan.sequential_card_gap_ms===5000);
add('B02-S12','card gap overflow',form({page:U,queue:U,steps:'Собери публичные данные лотов из очереди пакетом 1.',gap:'2147483648 мс'}),'reject gap overflow',p=>!p.valid&&p.errors.includes('UI_PLAN_CARD_GAP_OUT_OF_RANGE'));
const out={block:'02 parser/validator',results:cases,pass:cases.filter(x=>x.status==='PASS').length,fail:cases.filter(x=>x.status==='FAIL').length};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify({pass:out.pass,fail:out.fail},null,2));if(out.fail)process.exit(1);
