'use strict';
const fs=require('node:fs'),path=require('node:path');const {loadWorker}=require('../helpers/worker_vm.cjs');
const ROOT=path.resolve(__dirname,'../..'),OUT=process.env.AF_SCENARIO_OUT||path.join(ROOT,'qa/v134/blocks/block03.json');
const URL='https://www.avito.ru/moskva/tovary_dlya_kompyutera/monitor_27_ips_8348999864';
const VALID=`Режим:\nAVITO_UI\nСтраница:\n${URL}\nШаги:\nСобери до 20 видимых карточек.`;
const INVALID=`Режим:\nAVITO_UI\nСтраница:\n${URL}\nПроверка:\npartial only`;
function baseState(w,extra={}){return w.C.makeState({search_id:'run',operation_id:'run:old',status:'WAITING_FOR_NEXT_ASSISTANT_FORM',phase:'CHATGPT_CONTINUATION',user_started:true,current_window_id:2,chatgpt_tab_id:1,chatgpt_window_id:2,chat_origin:w.identity.origin,chat_path:w.identity.chat_path,conversation_id:w.identity.conversation_id,anchor_turn_id:'anchor',...extra});}
function candidate(w,text,extra={}){return {run_id:'run',anchor_turn_id:'anchor',assistant_turn_id:'assist',origin:w.identity.origin,chat_path:w.identity.chat_path,conversation_id:w.identity.conversation_id,prompt_text:text,payload_extracted:true,payload_bytes:Buffer.byteLength(text),form_key:`anchor|assist|${w.C.fingerprint(text)}`,...extra};}
const results=[];async function run(id,name,input,expected,fn){let actual={},status='FAIL';try{actual=await fn();status=actual.pass?'PASS':'FAIL';}catch(e){actual={error:String(e),stack:e.stack}}results.push({id,name,input,emulation:'production service_worker.js in Chrome API VM',expected,actual,status});}
(async()=>{
 await run('B03-S01','valid payload accepted','waiting state + complete valid AVITO_UI candidate','accepted; no unvalidated durable state',async()=>{const w=loadWorker();try{await w.h.saveState(baseState(w));const r=await w.h.handleFullText({candidate:candidate(w,VALID)},{tab:{...w.tabs.get(1)}});const s=await w.h.getState();return {response:r.data?.reason||r.data?.disposition,status:s.status,last_key:!!s.last_consumed_form_key,pass:r.data?.accepted===true&&s.status!=='FORM_TEXT_CAPTURED_UNVALIDATED'};}finally{w.dispose();}});
 await run('B03-S02','invalid payload reports validation','waiting state + stable invalid command','validation report delivered/continuation; no Avito mutation',async()=>{const w=loadWorker();try{await w.h.saveState(baseState(w));const r=await w.h.handleFullText({candidate:candidate(w,INVALID)},{tab:{...w.tabs.get(1)}});const nav=w.calls.filter(x=>x[0]==='navigate'||x[0]==='reload').length;return {reason:r.data?.reason,validation_reported:r.data?.validation_error_reported,nav,pass:r.data?.reason==='COMMAND_INVALID_AFTER_FULL_COPY'&&nav===0};}finally{w.dispose();}});
 await run('B03-S03','legacy unvalidated state recovery','FORM_TEXT_CAPTURED_UNVALIDATED from <=1.0.33','read-only reset to waiting; form key cleared',async()=>{const w=loadWorker();try{await w.h.saveState(baseState(w,{status:'FORM_TEXT_CAPTURED_UNVALIDATED',last_consumed_form_key:'anchor|assist|660:deadbeef',assistant_turn_id:'assist'}));await w.h.recoverRuntimeOnWake();const s=await w.h.getState();return {status:s.status,last_key:s.last_consumed_form_key,blocked:s.blocked_reason,pass:s.status==='WAITING_FOR_NEXT_ASSISTANT_FORM'&&!s.last_consumed_form_key&&!s.blocked_reason};}finally{w.dispose();}});
 await run('B03-S04','larger same-turn supersedes unsent validation','REPORT_READY_IN_COMPOSER from 660-char partial; same assistant yields 6800-ish full payload','owned staged validation discarded; larger payload accepted',async()=>{const w=loadWorker({onMessage:(id,msg,done,{finish})=>{if(msg.type==='AF_CAPTURE_DISCARD_OWNED_REPORT_STAGE'){finish(done,{ok:true,cleared:true});return true;}return false;}});try{await w.h.saveState(baseState(w,{status:'REPORT_READY_IN_COMPOSER',report_kind:'validation_error',report:'validator report',report_send_attempted:false,report_delivery_id:'d1',assistant_turn_id:'assist',last_consumed_form_key:'anchor|assist|660:deadbeef'}));const full=VALID+'\nПроверка:\n'+('x'.repeat(7000));const r=await w.h.handleFullText({candidate:candidate(w,full)},{tab:{...w.tabs.get(1)}});return {accepted:r.data?.accepted,reason:r.data?.reason,discard_calls:w.calls.filter(x=>x[0]==='message'&&x[2]==='AF_CAPTURE_DISCARD_OWNED_REPORT_STAGE').length,pass:r.data?.accepted===true&&w.calls.some(x=>x[0]==='message'&&x[2]==='AF_CAPTURE_DISCARD_OWNED_REPORT_STAGE')};}finally{w.dispose();}});
 await run('B03-S05','same-size payload cannot supersede','unsent validation from 660; same turn candidate <=660 bytes','COMMAND_ALREADY_IN_FLIGHT; no stage discard',async()=>{const w=loadWorker({onMessage:(id,msg,done,{finish})=>{if(msg.type==='AF_CAPTURE_DISCARD_OWNED_REPORT_STAGE'){finish(done,{ok:true,cleared:true});return true;}return false;}});try{await w.h.saveState(baseState(w,{status:'REPORT_READY_IN_COMPOSER',report_kind:'validation_error',report:'validator',report_send_attempted:false,assistant_turn_id:'assist',last_consumed_form_key:'anchor|assist|660:deadbeef'}));const r=await w.h.handleFullText({candidate:candidate(w,VALID)},{tab:{...w.tabs.get(1)}});return {reason:r.data?.reason,discard:w.calls.some(x=>x[0]==='message'&&x[2]==='AF_CAPTURE_DISCARD_OWNED_REPORT_STAGE'),pass:r.data?.reason==='COMMAND_ALREADY_IN_FLIGHT'&&!w.calls.some(x=>x[0]==='message'&&x[2]==='AF_CAPTURE_DISCARD_OWNED_REPORT_STAGE')};}finally{w.dispose();}});
 await run('B03-S06','different assistant cannot supersede','larger candidate but assistant_turn_id differs','COMMAND_ALREADY_IN_FLIGHT; no discard',async()=>{const w=loadWorker({onMessage:(id,msg,done,{finish})=>{if(msg.type==='AF_CAPTURE_DISCARD_OWNED_REPORT_STAGE'){finish(done,{ok:true,cleared:true});return true;}return false;}});try{await w.h.saveState(baseState(w,{status:'REPORT_READY_IN_COMPOSER',report_kind:'validation_error',report:'validator',report_send_attempted:false,assistant_turn_id:'assist-old',last_consumed_form_key:'anchor|assist-old|660:deadbeef'}));const r=await w.h.handleFullText({candidate:candidate(w,VALID+'\n'+('x'.repeat(1000)),{assistant_turn_id:'assist-new'})},{tab:{...w.tabs.get(1)}});return {reason:r.data?.reason,pass:r.data?.reason==='COMMAND_ALREADY_IN_FLIGHT'};}finally{w.dispose();}});
 await run('B03-S07','clicked report cannot be superseded','larger same-turn payload but report_send_attempted=true','COMMAND_ALREADY_IN_FLIGHT; never clear after irreversible Send boundary',async()=>{const w=loadWorker({onMessage:(id,msg,done,{finish})=>{if(msg.type==='AF_CAPTURE_DISCARD_OWNED_REPORT_STAGE'){finish(done,{ok:true,cleared:true});return true;}return false;}});try{await w.h.saveState(baseState(w,{status:'REPORT_DELIVERY_UNCERTAIN',report_kind:'validation_error',report:'validator',report_send_attempted:true,assistant_turn_id:'assist',last_consumed_form_key:'anchor|assist|660:deadbeef'}));const r=await w.h.handleFullText({candidate:candidate(w,VALID+'\n'+('x'.repeat(1000)))},{tab:{...w.tabs.get(1)}});return {reason:r.data?.reason,pass:r.data?.reason==='COMMAND_ALREADY_IN_FLIGHT'};}finally{w.dispose();}});
 await run('B03-S08','stage ownership refusal blocks supersede','larger same-turn payload but composer refuses exact owned-stage discard','remain in-flight; no replacement command',async()=>{const w=loadWorker({onMessage:(id,msg,done,{finish})=>{if(msg.type==='AF_CAPTURE_DISCARD_OWNED_REPORT_STAGE'){finish(done,{ok:true,cleared:false,reason:'OWNED_REPORT_STAGE_NOT_CONFIRMED'});return true;}return false;}});try{await w.h.saveState(baseState(w,{status:'REPORT_READY_IN_COMPOSER',report_kind:'validation_error',report:'validator',report_send_attempted:false,assistant_turn_id:'assist',last_consumed_form_key:'anchor|assist|660:deadbeef'}));const r=await w.h.handleFullText({candidate:candidate(w,VALID+'\n'+('x'.repeat(1000)))},{tab:{...w.tabs.get(1)}});const s=await w.h.getState();return {reason:r.data?.reason,status:s.status,pass:r.data?.reason==='COMMAND_ALREADY_IN_FLIGHT'&&s.status==='REPORT_READY_IN_COMPOSER'};}finally{w.dispose();}});
 const out={block:'03 worker payload ownership/supersede',results,pass:results.filter(x=>x.status==='PASS').length,fail:results.filter(x=>x.status==='FAIL').length};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify({pass:out.pass,fail:out.fail},null,2));if(out.fail)process.exit(1);
})();
