'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {loadWorker}=require('./helpers/worker_vm.cjs');
const legacy='Текст в поле изменён после подготовки; пользовательский текст не отправлен и не перезаписан.';
function fixture(response_state='staged',send_reply){return loadWorker({onMessage(id,m,done,x){
 if(m.type==='AF_CAPTURE_RECONCILE_REPORT'){x.finish(done,{ok:true,state:response_state,anchor_turn_id:response_state==='confirmed'?'confirmed-report':null,identity:x.identity});return true;}
 if(m.type==='AF_CAPTURE_SEND_REPORT'&&send_reply){x.finish(done,send_reply);return true;}
}});}
async function seed(w,extra={}){return w.seed({status:'REPORT_DELIVERY_BLOCKED',report:'saved report',report_kind:'ui_action_plan',report_delivery_id:'saved-id',report_send_attempted:false,...extra});}
for(const state of ['staged','empty']) test('explicit Continue retries one proven pre-click report from '+state,async()=>{const w=fixture(state);try{await seed(w);const r=await w.h.continueReport();assert.equal(r.ok,true);assert.equal(w.sent.length,1);assert.equal(w.sent[0].report_text,'saved report');assert.equal((await w.h.getState()).status,'WAITING_FOR_NEXT_ASSISTANT_FORM');assert.equal(w.calls.filter(c=>c[0]==='navigate'||c[0]==='reload').length,0);}finally{w.dispose();}});
for(const attempted of [true,null])test('Continue never retries sent/uncertain report attempt='+attempted,async()=>{const w=fixture();try{await seed(w,{report_send_attempted:attempted});await w.h.continueReport();assert.equal(w.sent.length,0);assert.equal((await w.h.getState()).report,'saved report');}finally{w.dispose();}});
test('watchdog reconciliation stays read-only even for proven pre-click failure',async()=>{const w=fixture();try{const s=await seed(w);await w.h.reconcileBlockedReport(s);assert.equal(w.sent.length,0);assert.equal((await w.h.getState()).status,'REPORT_READY_IN_COMPOSER');}finally{w.dispose();}});
test('legacy v125 failure proof survives read-only reconciliation then explicit Continue',async()=>{const w=fixture();try{const s=await seed(w,{report_send_attempted:undefined,blocked_reason:legacy});await w.h.reconcileBlockedReport(s);assert.equal((await w.h.getState()).report_send_attempted,false);await w.h.continueReport();assert.equal(w.sent.length,1);}finally{w.dispose();}});
test('foreign composer never overwritten; saved report retained',async()=>{const w=fixture('occupied');try{await seed(w);await w.h.continueReport();assert.equal(w.sent.length,0);assert.equal((await w.h.getState()).report,'saved report');assert.equal((await w.h.getState()).status,'PAUSED_USER_COMPOSER_OCCUPIED');}finally{w.dispose();}});
test('exact confirmed user turn reconciles without second Send',async()=>{const w=fixture('confirmed');try{await seed(w,{report_send_attempted:true});await w.h.continueReport();assert.equal(w.sent.length,0);assert.equal((await w.h.getState()).report,null);assert.equal((await w.h.getState()).anchor_turn_id,'confirmed-report');}finally{w.dispose();}});
test('adapter pre-click return persists code and false, no guessed success',async()=>{const w=fixture('staged',{ok:false,code:'REPORT_TEXT_ROUNDTRIP_MISMATCH',error:'fixture readback mismatch',send_attempted:false});try{const s=await seed(w);await w.h.deliverReportToPinnedChat(s,s.report,s.report_kind);const after=await w.h.getState();assert.equal(after.report_send_attempted,false);assert.equal(after.report_delivery_error_code,'REPORT_TEXT_ROUNDTRIP_MISMATCH');assert.equal(after.report,'saved report');}finally{w.dispose();}});
test('unknown reply is not promoted to pre-click certainty',async()=>{const w=fixture('staged',{ok:false,code:'REPORT_TRANSPORT_FAILED',error:'fixture transport timeout'});try{const s=await seed(w);await w.h.deliverReportToPinnedChat(s,s.report,s.report_kind);assert.equal((await w.h.getState()).report_send_attempted,null);}finally{w.dispose();}});
test('report occupied pause has priority over continuing collection queue',async()=>{const w=fixture('empty');try{await seed(w,{status:'PAUSED_USER_COMPOSER_OCCUPIED',sequential_review:{status:'paused_for_connection',cursor:3,candidates:[]}});await w.h.continueReport();assert.equal(w.sent.length,1);assert.equal(w.calls.filter(c=>c[0]==='message'&&c[2]==='AF_EXECUTE_AVITO_UI_PLAN').length,0);}finally{w.dispose();}});
