#!/usr/bin/env python3
import json, re, sys, hashlib
from pathlib import Path
cur=Path(sys.argv[1]); early=Path(sys.argv[2]); nested_dir=Path(sys.argv[3]); out=Path(sys.argv[4]); out.mkdir(parents=True,exist_ok=True)
raw=json.loads((cur/'FULL_HISTORY_RAW.json').read_text())
earlyj=json.loads((early/'EARLY_HISTORY.json').read_text())
nested=json.loads((nested_dir/'NESTED_HISTORY.json').read_text())
def vk(v):
 try:return tuple(map(int,v.split('.')))
 except:return (999,999,999)
def purpose(n):
 x=re.sub(r'^AVITO_FINDER_v\d+\.\d+\.\d+_','',n,flags=re.I);x=re.sub(r'_TEST_CANDIDATE(?: \(1\))?\.zip$','',x,flags=re.I);x=re.sub(r'_candidate\.zip$','',x,flags=re.I);return re.sub(r'\.zip$','',x,flags=re.I)
adj={d['to']:[x['file'] for x in d['stats']] for d in nested['unambiguous_adjacent_diffs']}
archives=[]
for r in sorted(nested['archives'],key=lambda x:(vk(x.get('version_from_filename')),x['archive'])):
 c=r['candidates'][0] if r.get('candidates') else None
 archives.append({'version':r.get('version_from_filename'),'archive':r['archive'],'intent':purpose(r['archive']),'status':r['status'],'sha256':r['archive_sha256'],'bytes':r['archive_bytes'],'manifest_version':c.get('manifest_version') if c else None,'runtime_bundle_sha256':c.get('runtime_bundle_sha256') if c else None,'runtime_files':sorted(c.get('runtime_files',{})) if c else [],'tests':c.get('test_count',0) if c else 0,'markers':c.get('markers',{}) if c else {}})
later=[
('1.0.2','VERSION_NOT_CONFIRMED','Нет version-specific archive/commit/history-doc authority; существование отдельного релиза не предполагается.'),('1.0.3','VERSION_NOT_CONFIRMED','Нет version-specific authority.'),('1.0.4','VERSION_NOT_CONFIRMED','Нет version-specific authority.'),('1.0.5','VERSION_NOT_CONFIRMED','Нет version-specific authority.'),
('1.0.6','PARTIAL_HISTORICAL_AUTHORITY','Materializer/README заявляет SHA 32e1523e…, но preserved pre-materialization Base64 stream даёт SHA 0b6adbc7… и не является валидным exact package; byte-exact source не подменяется.'),
('1.0.7','DOC_HASH_AUTHORITY_SOURCE_UNAVAILABLE','Page-ready DOM fallback + navigation commit guard + bounded polling; manual CAPTCHA; historical ZIP SHA 6f2e83a2…; 55/55.'),
('1.0.8','DOC_AUTHORITY_SOURCE_UNAVAILABLE','Первая Proxy.Market версия: Avito-only PAC, manual profiles/auth, session secrets, без auto-rotation.'),
('1.0.9','DOC_AUTHORITY_SOURCE_UNAVAILABLE','Proxy Data Saver/traffic meter; DNR heavy-media only; no auto-rotation.'),
('1.0.10','DOC_AUTHORITY_SOURCE_UNAVAILABLE','Key/package discovery; дефект: package lookup мог ложно пометить валидный key invalid; aggressive pagination.'),
('1.0.11','DOC_AUTHORITY_SOURCE_UNAVAILABLE','Key validity отделена от package discovery; packages best-effort warning.'),
('1.0.12','DOC_AUTHORITY_SOURCE_UNAVAILABLE','Manual endpoint create; documented rotation semantics: -1 sticky, 0 every request; no auto IP-block creation.'),
('1.0.13','DOC_AUTHORITY_SOURCE_UNAVAILABLE','Residential package/profile compatibility and gateway normalization; manual switch.'),
('1.0.14','BEHAVIORAL_AUTHORITY_FROM_V15','Exact source не найден; predecessor behavior: credentials once/request and HTTPS-only, multiple Chrome challenges leaked to native prompt.'),
('1.0.15','DOC_TEST_AUTHORITY_SOURCE_UNAVAILABLE','Auth fix: up to 3 matching challenges, HTTP+HTTPS, challenger bound; 93/93.'),
('1.0.16','DOC_TEST_AUTHORITY_SOURCE_UNAVAILABLE','Proxy UI/storage cleanup; regression: user_started=true overblocked proxy mutation; 100/100.'),
('1.0.17','DOC_TEST_AUTHORITY_SOURCE_UNAVAILABLE','State-specific proxy mutation gate; 101/101.'),
('1.0.18','DOC_TEST_AUTHORITY_SOURCE_UNAVAILABLE','Visible AVITO_IP_BLOCK + bounded reload; defect: new timeOrigin/document mistaken for recovery; 106/106.'),
('1.0.19','DOC_TEST_AUTHORITY_SOURCE_UNAVAILABLE','bypassCache + main-frame telemetry; proves fresh request, not new egress; 108/108.'),
('1.0.20','VERSION_SPECIFIC_AUTHORITY_NOT_FOUND','Git/File Library search found no version-specific authority; no changes assigned.'),('1.0.21','VERSION_SPECIFIC_AUTHORITY_NOT_FOUND','Git/File Library search found no version-specific authority; no changes assigned.'),
('1.0.22','LIVE_LOG_AUTHORITY_SOURCE_UNAVAILABLE','Profile failover every-request→sticky on same gateway without measured egress; profile change incorrectly stood in for new IP; readiness/network race.'),
('1.0.23','EXACT_SOURCE','Verify→rotate→verify with IP canaries and transport epochs; fallback creates rotation=0 endpoint. Missing invariant: changed canary IP != stable multi-request Avito session.'),
('1.0.24','EXACT_SOURCE','Collection-first IP-block recovery/replay; preserves counter; inherits rotation=0 fallback.'),
('1.0.25','PRESERVED_TEST_AUTHORITY','Unified recovery/replay/cancellation/egress/queue/version/provider-create regression family.'),('1.0.26','PRESERVED_TEST_AUTHORITY','Report delivery: retry only proven pre-click; uncertain/sent read-only; no blind second Send.'),('1.0.27','PRESERVED_TEST_AUTHORITY','Durable navigation intent + report send receipt/ACK budgets + op fencing.'),('1.0.28','PRESERVED_TEST_AUTHORITY','Unified 429/rate-limit recovery, bounded/cancellable.'),('1.0.29','PRESERVED_TEST_AUTHORITY','Contract audit: queue persistence, Retry-After, proxy restore, provider POST uncertainty, same-chat/report/direct-delivery constraints.'),('1.0.30','PRESERVED_TEST_REPRO_AUTHORITY','about:blank trampoline regression: pendingUrl=about:blank prevented target dispatch; cursor=0 transient_blank timeout.'),
('1.0.31','PATCH_DOC_TEST_AUTHORITY','Exact-target child create restored; durable target intent/receipt; owned-child adoption; legacy blank migration; proxy remains transport.'),('1.0.32','PATCH_DOC_TEST_AUTHORITY','Bounded report Send discovery/manual-send reconciliation; no blind resend.'),('1.0.33','PATCH_DOC_TEST_AUTHORITY','Exact Writing Block-only execution + ordinary Markdown zero-command + manual CAPTCHA re-anchor.'),
('1.0.34','EXACT_SOURCE','Writing Block body-stability/finality + validation-before-ownership + safe same-turn supersede; 128 scenario matrix.'),('1.0.35','EXACT_SOURCE_REJECTED','Manifest 1.0.35 but actual Avito adapter PING 1.0.34; aggregate 9 groups PASS/15 FAIL; rejected.'),('1.0.36','EXACT_SOURCE_R2','Minimal manifest/adapter identity fix; R1 test-VM disposal hang; R2 test-only cleanup; 35/35; proxy runtime unchanged.'),('1.0.37','EXACT_SOURCE_LIVE_REJECTED','Proxy telemetry/state integrity. Offline 35/35, live recovery exhausted at TOP queue cursor 0/3.'),('1.0.38','EXACT_SOURCE_CURRENT_MAIN','Recovery-created endpoint rotation 0→-1 sticky; exact provider request-body RED/GREEN; 35/35; Node 368/368; remote readback; live acceptance NOT_RUN.')]
regs=[
('v1.0.6→7','tab.status complete only; usable DOM loading timed out','v1.0.7','DOM-ready fallback + commit guard'),('v1.0.14','one auth/request + HTTPS-only','v1.0.15','multi-challenge HTTP/HTTPS challenger-bound'),('v1.0.16','user_started conflated open run with active step','v1.0.17','state-specific mutation gate'),('v1.0.18','new document/timeOrigin treated as recovery','v1.0.19','bypassCache/main-frame freshness'),('v1.0.19/22','fresh request/profile change treated as egress change','v1.0.23','measured canary egress, no reload without proof'),('v1.0.22','readiness/network race + unproven failover egress','v1.0.23/25','recovery/readiness evidence tests'),('v1.0.23','rotation=0 can change canary IP but destabilize multi-request Avito session','v1.0.38','provider create body rotation=-1 + sticky reconcile'),('v1.0.30','about:blank pendingUrl prevented target dispatch','v1.0.31','exact target create + transient-blank reproduction'),('v1.0.31','manual report Send/restart uncertainty','v1.0.32','send intent/receipt read-only reconciliation'),('v1.0.32','ordinary code block mistaken for Writing Block; CAPTCHA anchor gap','v1.0.33','Writing Block-only + CAPTCHA handoff'),('v1.0.33','toolbar ready before Writing Block body final','v1.0.34','body fingerprint stability + validation before ownership'),('v1.0.35','manifest != actual adapter PING','v1.0.36','actual adapter identity regression'),('v1.0.36 live','proxy diagnostic level/state defects','v1.0.37','10 static + 6 dynamic telemetry/state tests'),('v1.0.37 live','endpoint rotation semantics untested','v1.0.38','exact provider create HTTP-body regression')]
md=['# PRE-PATCH FULL HISTORY AUDIT — Avito Finder','', '**Дата:** 2026-09-13  ','**Статус:** `FULL_HISTORY_AUDIT=PASS`  ','**Текущий release:** v1.0.38 остаётся `LIVE_UNVERIFIED`; этот PASS закрывает только Rule 20 history gate.','', '## 1. Охват','',f"- Reachable Git: {raw['commit_count']} commits; runtime/test/history commits: {len(raw['patch_commits'])}; refs: {len(raw['refs'])}; PR: {len(raw['pull_requests'])}.",f"- Historical History.zip: {len(archives)} archive variants; {len(set(x['version'] for x in archives))} unique versions v0.1.0–v1.0.1; exact runtime manifests: {sum(x['status']=='EXACT_ARCHIVE_SOURCE' for x in archives)}.",f"- Unambiguous historical adjacent runtime diffs: {len(nested['unambiguous_adjacent_diffs'])}. v0.6.1 intentionally remains two distinct runtime variants.",'- Current exact roots: v1.0.23, v1.0.24, v1.0.34–v1.0.38. Source gaps are explicit below; no version is reconstructed by guess.','- Audit-only workflows enforce no manifest/runtime changes. Invalid audit-harness runs were rejected, not counted as evidence.','', '## 2. Главный вывод','', 'Inherited `rotation=0` recovery policy existed at least in exact v1.0.23 and exact v1.0.24 and survived through v1.0.37. Previous analysis was too selective. v1.0.23 measured canary egress changes, but lacked the distinct invariant **canary IP change != stable multi-request Avito browser session**. v1.0.38 closes that specific gap with an exact provider create request-body regression requiring sticky `rotation=-1`.','', '## 3. Exact archived lineage v0.1.0–v1.0.1','', '| Version | Archive variant | Intent | Status | Tests | Changed runtime from prior unambiguous version |','|---|---|---|---|---:|---|']
for a in archives:
 ch=', '.join(adj.get(a['version'],[])) if a['status']=='EXACT_ARCHIVE_SOURCE' else ''
 md.append(f"| {a['version']} | `{a['archive']}` | `{a['intent']}` | {a['status']} | {a['tests']} | {ch} |")
md += ['', '### Milestones confirmed by exact archived code','', '- v0.2.0 assistant/command anchoring; v0.2.1 Writing Block capture.', '- v0.4.3 page-ready lineage; v0.5.0 DIALOG_VISIBLE.', '- v0.9.0 optional-login markers; v0.9.10 about:blank mechanism; v0.9.12 sequential machinery.', '- v1.0.0 explicit listing queue. No proxy markers through exact v1.0.1.', '', '## 4. v1.0.2–v1.0.38 authority ledger','', '| Version | Authority | Result |','|---|---|---|']
for v,a,r in later:md.append(f'| {v} | {a} | {r} |')
md += ['', '## 5. Critical state-machine evolution','', '| State machine | Evolution | Permanent boundary |','|---|---|---|',
'| ChatGPT capture/validator | v0.2.x anchor/Writing Block → v1.0.33 ordinary zero-command → v1.0.34 body stability | Writing Block only; ordinary text/code never executable; toolbar readiness != body finality. |','| Navigation/owned child | early visible UI → v0.7/0.8 handoff/ownership → v1.0.30 blank regression → v1.0.31 exact-target restore | Proxy cannot own target navigation; exact target + durable intent/receipt. |','| Queue/cursor | v0.9.12 sequential → v1.0.0 explicit queue → v1.0.25+ checkpoint authority | Assistant order preserved; observation/cursor before close; recovery never resets baseline. |','| Report delivery | early reports → v1.0.26/27 receipts → v1.0.32 manual reconciliation | Never blind-resend uncertain report; same pinned chat. |','| Proxy/auth | v1.0.8 Avito-only PAC → v1.0.12 endpoint semantics → v1.0.15 auth → v1.0.17 mutation gate | Proxy is transport; exact PAC ownership; challenger-bound auth; mutate by active step. |','| Rotation/egress | v1.0.12 -1 sticky/0 every request → v1.0.22 bad failover inference → v1.0.23 canary proof + rotation0 fallback → v1.0.38 sticky fallback | profile/request/canary IP/session stability are separate evidence levels. |','| IP/rate/CAPTCHA | v1.0.18 IP block → v1.0.19 request freshness → v1.0.23 egress → v1.0.25 unified recovery → v1.0.28 429 → v1.0.33 manual CAPTCHA → v1.0.37 mixed telemetry | CAPTCHA manual; bounded recovery; durable provider intent; exact terminal reason. |','', '## 6. Real defect → regression closure','', '| Exposed | Defect | Closed | Regression authority |','|---|---|---|---|']
for a,b,c,d in regs:md.append(f'| {a} | {b} | {c} | {d} |')
md += ['', '## 7. Исторические границы','', f"- v1.0.6 exact package unresolved: advertised SHA `{earlyj['v1.0.6']['advertised_sha256']}`, preserved stream SHA `{earlyj['v1.0.6']['reconstructed_sha256']}`, hash_match={earlyj['v1.0.6']['hash_match']}, extractable={earlyj['v1.0.6']['zip_extractable']}.", '- v1.0.2–v1.0.5: VERSION_NOT_CONFIRMED; не найдено отдельной authority.', '- v1.0.20/v1.0.21: VERSION_SPECIFIC_AUTHORITY_NOT_FOUND; изменения не приписываются.', '- v1.0.14, v1.0.22 and v1.0.25–v1.0.33 have bounded non-exact authority as documented in the ledger.', '', '## 8. Process failures found','', '1. Выборочный анализ «ключевых» версий пропустил inherited rotation=0 lineage.', '2. v1.0.23 regression measured canary egress, not stable Avito session — wrong abstraction level for the eventual live failure.', '3. Offline PASS repeatedly did not equal installed acceptance; v1.0.37 is the clearest example.', '4. Harness errors in v1.0.37/v1.0.38 and this audit are preserved separately and never counted as runtime evidence.', '5. Source availability gaps are explicit; no missing version/source is silently invented.', '', '## 9. Rule 20 acceptance','', '`FULL_HISTORY_AUDIT=PASS` because every discovered historical archive variant, reachable runtime/test/history commit, ref and PR was inventoried; exact code was read/diffed where available; source gaps were exhaustively marked; known live defects were mapped to regression closure; and audit-only gates prove runtime remained unchanged.', '', '**This PASS does not accept v1.0.38 live.** v1.0.38 remains `NOT_RUN / LIVE_UNVERIFIED` until installed Chrome E2E.', '', '## 10. Evidence','', '- Current-history scanner: run `34740844051`.', '- Early historical scan: run `34741618622` (first harness failure retained; second run success and v1.0.6 mismatch preserved).', '- Nested exact archive scan: run `34741795769`.', '- Machine evidence saved alongside this report: `FULL_HISTORY_RAW.json`, `NESTED_HISTORY.json`, `EARLY_HISTORY.json`, summaries and adjacent-diff index.', '- Rule 20: `PATCH_ENGINEERING_RULES.md`.','']
mdtxt='\n'.join(md)
(out/'PRE_PATCH_FULL_HISTORY_AUDIT_2026-09-13.md').write_text(mdtxt,encoding='utf-8')
structured={'schema':'avito_finder_full_history_audit_v1','date':'2026-09-13','status':'PASS','runtime_patch_during_audit':False,'current_release':'1.0.38','current_release_live_acceptance':'NOT_RUN_LIVE_UNVERIFIED','runs':{'current_history':34740844051,'early_history':34741618622,'nested_history':34741795769},'coverage':{'reachable_commits':raw['commit_count'],'runtime_test_history_commits':len(raw['patch_commits']),'refs':len(raw['refs']),'prs':len(raw['pull_requests']),'historical_archive_variants':len(archives),'historical_unique_versions':len(set(x['version'] for x in archives)),'historical_exact_runtimes':sum(x['status']=='EXACT_ARCHIVE_SOURCE' for x in archives),'historical_adjacent_diffs':len(nested['unambiguous_adjacent_diffs'])},'early_archives':archives,'later_versions':[{'version':v,'authority':a,'result':r} for v,a,r in later],'regression_closure':[{'exposed':a,'defect':b,'closed':c,'regression':d} for a,b,c,d in regs],'v1.0.6':earlyj['v1.0.6'],'major_finding':{'rotation0_lineage':'exact v1.0.23 → exact v1.0.24 → … → v1.0.37','missing_invariant':'canary IP change != stable multi-request Avito browser session','closed_by':'v1.0.38 provider create request body rotation=-1 sticky regression'},'unconfirmed_versions':['1.0.2','1.0.3','1.0.4','1.0.5'],'version_specific_authority_not_found':['1.0.20','1.0.21']}
(out/'PRE_PATCH_FULL_HISTORY_AUDIT_2026-09-13.json').write_text(json.dumps(structured,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
receipt={'status':'PASS','md_sha256':hashlib.sha256((out/'PRE_PATCH_FULL_HISTORY_AUDIT_2026-09-13.md').read_bytes()).hexdigest(),'json_sha256':hashlib.sha256((out/'PRE_PATCH_FULL_HISTORY_AUDIT_2026-09-13.json').read_bytes()).hexdigest(),'source_runs':[34740844051,34741618622,34741795769]}
(out/'PRE_PATCH_FULL_HISTORY_AUDIT_2026-09-13_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n')
print(json.dumps(receipt))
